version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    PYTHONPATH: /opt/airflow/hr_project
    DB_HOST: host.docker.internal
    DB_PORT: "5432"
    DB_NAME: hr_source_db
    DB_USER: postgres
    DB_PASSWORD: admin123
    SOURCE_SCHEMA: public
    WAREHOUSE_SCHEMA: hr_warehouse
    
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - ../02_etl_pipeline:/opt/airflow/hr_project
  depends_on:
    postgres-airflow:
      condition: service_healthy

services:
  # Separate postgres ONLY for Airflow metadata
  # NOT your hr_source_db — that stays on localhost:5432
  postgres-airflow:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    ports:
      - "5433:5432"   # 5433 on host — avoids conflict with your 5432

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db init &&
               airflow users create
               --username admin
               --password admin
               --firstname Lakshmi
               --lastname Praba
               --role Admin
               --email lakshmipraba23.01@gmail.com"
    depends_on:
      postgres-airflow:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"   # 8081 on host — avoids conflict with retail on 8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
